#ifndef CPPRL_DOCTEST_DISABLE_H
#define CPPRL_DOCTEST_DISABLE_H

#ifndef DOCTEST_CONFIG_NO_DEBUGGER
#define DOCTEST_CONFIG_NO_DEBUGGER
#endif

#ifndef DOCTEST_CONFIG_DISABLE_EXCEPTIONS  
#define DOCTEST_CONFIG_DISABLE_EXCEPTIONS
#endif

#ifndef DOCTEST_CONFIG_NO_POSIX_SIGNALS
#define DOCTEST_CONFIG_NO_POSIX_SIGNALS 
#endif

#ifndef DOCTEST_CONFIG_DISABLE_DEBUGGER_BREAK
#define DOCTEST_CONFIG_DISABLE_DEBUGGER_BREAK
#endif

#ifndef DOCTEST_CONFIG_NO_INLINE_ASM
#define DOCTEST_CONFIG_NO_INLINE_ASM
#endif

#ifndef DOCTEST_CONFIG_NO_TRY_CATCH_IN_ASSERTS
#define DOCTEST_CONFIG_NO_TRY_CATCH_IN_ASSERTS
#endif

#endif // CPPRL_DOCTEST_DISABLE_H
